# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'setup-k6-action Internal Documentation'
repo_url: https://github.com/grafana/setup-k6-action
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
